// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS_Project.Data;

#nullable disable

namespace TMS_Project.Migrations
{
    [DbContext(typeof(TmsDbContext))]
    [Migration("20260428094053_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS_Project.Models.Camion", b =>
                {
                    b.Property<int>("CamionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CamionId"));

                    b.Property<int>("CapaciteKg")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAcquisition")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Immatriculation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransporteurId")
                        .HasColumnType("int");

                    b.HasKey("CamionId");

                    b.HasIndex("TransporteurId");

                    b.ToTable("Camion", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Chauffeur", b =>
                {
                    b.Property<int>("ChauffeurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChauffeurId"));

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPermis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransporteurId")
                        .HasColumnType("int");

                    b.HasKey("ChauffeurId");

                    b.HasIndex("TransporteurId");

                    b.ToTable("Chauffeur", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Cout", b =>
                {
                    b.Property<int>("CoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoutId"));

                    b.Property<DateTime>("DateCout")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Montant")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TourneeId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoutId");

                    b.HasIndex("TourneeId");

                    b.ToTable("Cout", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.DemandeLivraison", b =>
                {
                    b.Property<int>("DemandeLivraisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DemandeLivraisonId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CamionAffecteId")
                        .HasColumnType("int");

                    b.Property<int?>("ChauffeurAffecteId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("CommentaireValidation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSouhaitee")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionMarchandise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantEstime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroRecu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoidsKg")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DemandeLivraisonId");

                    b.HasIndex("ClientId");

                    b.ToTable("DemandeLivraison", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Livraison", b =>
                {
                    b.Property<int>("LivraisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivraisonId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRealisation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantEstime")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PoidsKg")
                        .HasColumnType("int");

                    b.Property<string>("StatutLivraison")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TourneeId")
                        .HasColumnType("int");

                    b.HasKey("LivraisonId");

                    b.HasIndex("ClientId");

                    b.HasIndex("TourneeId");

                    b.ToTable("Livraison", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Tournee", b =>
                {
                    b.Property<int>("TourneeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourneeId"));

                    b.Property<int>("CamionId")
                        .HasColumnType("int");

                    b.Property<int>("ChauffeurId")
                        .HasColumnType("int");

                    b.Property<decimal>("CoutTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("DateTournee")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontantEstime")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("StatutTournee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransporteurId")
                        .HasColumnType("int");

                    b.HasKey("TourneeId");

                    b.HasIndex("CamionId");

                    b.HasIndex("ChauffeurId");

                    b.HasIndex("TransporteurId");

                    b.ToTable("Tournee", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Transporteur", b =>
                {
                    b.Property<int>("TransporteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporteurId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransporteurId");

                    b.ToTable("Transporteur", (string)null);
                });

            modelBuilder.Entity("TMS_Project.Models.Camion", b =>
                {
                    b.HasOne("TMS_Project.Models.Transporteur", "Transporteur")
                        .WithMany("Camions")
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("TMS_Project.Models.Chauffeur", b =>
                {
                    b.HasOne("TMS_Project.Models.Transporteur", "Transporteur")
                        .WithMany("Chauffeurs")
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("TMS_Project.Models.Cout", b =>
                {
                    b.HasOne("TMS_Project.Models.Tournee", "Tournee")
                        .WithMany("Couts")
                        .HasForeignKey("TourneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournee");
                });

            modelBuilder.Entity("TMS_Project.Models.DemandeLivraison", b =>
                {
                    b.HasOne("TMS_Project.Models.Client", "Client")
                        .WithMany("DemandesLivraison")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("TMS_Project.Models.Livraison", b =>
                {
                    b.HasOne("TMS_Project.Models.Client", "Client")
                        .WithMany("Livraisons")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TMS_Project.Models.Tournee", "Tournee")
                        .WithMany("Livraisons")
                        .HasForeignKey("TourneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Tournee");
                });

            modelBuilder.Entity("TMS_Project.Models.Tournee", b =>
                {
                    b.HasOne("TMS_Project.Models.Camion", "Camion")
                        .WithMany("Tournees")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.Models.Chauffeur", "Chauffeur")
                        .WithMany("Tournees")
                        .HasForeignKey("ChauffeurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TMS_Project.Models.Transporteur", "Transporteur")
                        .WithMany("Tournees")
                        .HasForeignKey("TransporteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("Chauffeur");

                    b.Navigation("Transporteur");
                });

            modelBuilder.Entity("TMS_Project.Models.Camion", b =>
                {
                    b.Navigation("Tournees");
                });

            modelBuilder.Entity("TMS_Project.Models.Chauffeur", b =>
                {
                    b.Navigation("Tournees");
                });

            modelBuilder.Entity("TMS_Project.Models.Client", b =>
                {
                    b.Navigation("DemandesLivraison");

                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("TMS_Project.Models.Tournee", b =>
                {
                    b.Navigation("Couts");

                    b.Navigation("Livraisons");
                });

            modelBuilder.Entity("TMS_Project.Models.Transporteur", b =>
                {
                    b.Navigation("Camions");

                    b.Navigation("Chauffeurs");

                    b.Navigation("Tournees");
                });
#pragma warning restore 612, 618
        }
    }
}
